Global:
  # for mp2018 dataset, the property names are:
  # "formation_energy_per_atom",
  # "band_gap",
  # "G",
  # "K"
  label_names: ["formation_energy_per_atom"]
  do_train: True
  do_eval: False
  do_test: False

  graph_converter:
    __class_name__: FindPointsInSpheres
    __init_params__:
        cutoff: 4.0
        num_cpus: 10

Trainer:
  # Max epochs to train
  max_epochs: 2000
  # Random seed
  seed: 42
  # Save path for checkpoints and logs
  output_dir: ./output/megnet_mp2024_train_130k_e_form
  # Save frequency [epoch], for example, save_freq=10 means save checkpoints every 10 epochs
  save_freq: 100 # set 0 to disable saving during training
  # Logging frequency [step], for example, log_freq=10 means log every 10 steps
  log_freq: 20 # log frequency [step]

  # Start evaluation epoch, for example, start_eval_epoch=10 means start evaluation from epoch 10
  start_eval_epoch: 1
  # Evaluation frequency [epoch], for example, eval_freq=1 means evaluate every 1 epoch
  eval_freq: 1 # set 0 to disable evaluation during training
  # Pretrained model path, if null, no pretrained model will be loaded
  pretrained_model_path: null
  # Pretrained weight name, will be used when pretrained_model_path is a directory
  pretrained_weight_name: null #'latest.pdparams'
  # Resume from checkpoint path, useful for resuming training
  resume_from_checkpoint: null
  # whether use automatic mixed precision
  use_amp: False
  # automatic mixed precision level
  amp_level: 'O1'
  # whether run a model on no_grad mode during evaluation, useful for saving memory
  # If the model contains higher-order derivatives in the forward, it should be set to
  # False
  eval_with_no_grad: True
  # gradient accumulation steps, for example, gradient_accumulation_steps=2 means
  # gradient accumulation every 2 forward steps
  # Note:
  # one complete step  = gradient_accumulation_steps * forward steps + backward steps
  gradient_accumulation_steps: 1

  # best metric indicator, you can choose from "train_loss", "eval_loss", "train_metric", "eval_metric"
  best_metric_indicator: 'eval_metric' # "train_loss", "eval_loss", "train_metric", "eval_metric"
  # The name of the best metric, since you may have multiple metrics, such as "mae", "rmse", "mape"
  name_for_best_metric: "formation_energy_per_atom"
  # The metric whether is better when it is greater
  greater_is_better: False

  # compute metric during training or evaluation
  compute_metric_during_train: True # True: the metric will be calculated on train dataset
  metric_strategy_during_eval: 'epoch' # step or epoch, compute metric after step or epoch, if set to 'step', the metric will be calculated after every step, else after epoch

  # whether use visualdl, wandb, tensorboard to log
  use_visualdl: False
  use_wandb: False
  use_tensorboard: False

Model:
  __class_name__: MEGNetPlus
  __init_params__:
    dim_node_embedding: 16
    dim_edge_embedding: 100
    dim_state_embedding: 2
    nblocks: 3
    nlayers_set2set: 1
    niters_set2set: 2
    bond_expansion_cfg:
      rbf_type: "Gaussian"
      initial: 0.0
      final: 5.0
      num_centers: 100
      width: 0.5
    property_name: ${Global.label_names}
    data_mean: -1.6519
    data_std: 1.0694

Metric:
  formation_energy_per_atom:
    __class_name__: paddle.nn.L1Loss #MAEMetric
    __init_params__: {}

Optimizer:
  __class_name__: Adam
  __init_params__:
    beta1: 0.9
    beta2: 0.999
    lr:
      __class_name__: Cosine
      __init_params__:
        learning_rate: 0.001
        eta_min: 0.0001
        by_epoch: True

Dataset:
  train:
    dataset:
      __class_name__: MP2024Dataset
      __init_params__:
        path: "./data/mp2024_train_130k/mp2024_train.txt"
        property_names: ${Global.label_names}
        build_structure_cfg:
          format: dict
          num_cpus: 10
        build_graph_cfg: ${Global.graph_converter}
        cache_path: "./data/mp2024_train_130k_cache_find_points_in_spheres_cutoff_4/mp2024_train"
      num_workers: 4
      use_shared_memory: False
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: True
        drop_last: True
        batch_size: 128 # 128 for 1 GPUs, total batch size = 128 * 1 = 128
        
  val:
    dataset:
      __class_name__: MP2024Dataset
      __init_params__:
        path: "./data/mp2024_train_130k/mp2024_val.txt"
        property_names: ${Global.label_names}
        build_structure_cfg:
          format: dict
          num_cpus: 10
        build_graph_cfg: ${Global.graph_converter}
        cache_path: "./data/mp2024_train_130k_cache_find_points_in_spheres_cutoff_4/mp2024_val"
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 128

  test:
    dataset:
      __class_name__: MP2024Dataset
      __init_params__:
        path: "./data/mp2024_train_130k/mp2024_test.txt"
        property_names: ${Global.label_names}
        build_structure_cfg:
          format: dict
          num_cpus: 10
        build_graph_cfg: ${Global.graph_converter}
        cache_path: "./data/mp2024_train_130k_cache_find_points_in_spheres_cutoff_4/mp2024_test"
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 128


Predict:
  graph_converter: ${Global.graph_converter}
  eval_with_no_grad: True
