Global:
  epochs: 500
  output_dir: ./output/comformer_2d_0621_train_18k_e_form_finetune_e500_lr001
  save_freq: 100 # set 0 to disable saving during training
  log_freq: 10 # log frequency [step]
  start_eval_epoch: 1
  eval_freq: 1 # set 0 to disable evaluation during training
  seed: 42
  cal_metric_during_train: True # True: the metric will be calculated on train dataset
  pretrained_model_path: ./output/comformer_mp2024_train_130k_e_form/checkpoints/best.pdparams

Model:
  __name__: iComformer

Loss:
  __name__: LossWarper
  loss_fn:
    formation_energy_per_atom: # loss function for formation energy per atom
      __name__: MSELoss
  weights:
    formation_energy_per_atom: 1.0 # weight for formation energy per atom

Optimizer:
  __name__: AdamW
  lr:
    __name__: Cosine
    learning_rate: 0.001
    eta_min: 0.00001
    by_epoch: True

PostProcess:
  - Denormalize:
      mean: -1.3171
      std: 1.2241
      apply_keys: "formation_energy_per_atom" # apply normalization to this property

Metric:
  __name__: MetricWarper
  metric_fn:
    formation_energy_per_atom:
      __name__: MAEMetric
  main_indicator: formation_energy_per_atom # the main indicator to monitor and save model
  min_better: True

Dataset:
  train:
    dataset:
      __name__: CIFDataset
      csv_path: "./data/2d_0621_train_18k/train.csv"
      cif_path: './data/2d_0621_train_18k/cif_structure'
      converter_cfg:
        cutoff: 4.0
        method: comformer_graph
        num_cpus: 10
      transforms:
        - Normalize:
            mean: -1.3171
            std: 1.2241
            apply_keys: "formation_energy_per_atom" # apply normalization to this property
        - ClipData:
            min: -6.0
            apply_keys: "formation_energy_per_atom" # apply clip to this property
    loader:
      num_workers: 0
      use_shared_memory: False
    sampler:
      __name__: DistributedBatchSampler
      shuffle: True
      drop_last: True
      batch_size: 64
  val:
    dataset:
      __name__: CIFDataset
      csv_path: "./data/2d_0621_train_18k/val.csv"
      cif_path: './data/2d_0621_train_18k/cif_structure'
      converter_cfg:
        cutoff: 4.0
        method: comformer_graph
        num_cpus: 10
      transforms:
        - Normalize:
            mean: -1.3171
            std: 1.2241
            apply_keys: "formation_energy_per_atom" # apply normalization to this property
        - ClipData:
            min: -6.0
            apply_keys: "formation_energy_per_atom" # apply clip to this property
    sampler:
      __name__: BatchSampler
      shuffle: False
      drop_last: False
      batch_size: 32
  test:
    dataset:
      __name__: CIFDataset
      csv_path: "./data/2d_0621_train_18k/val.csv"
      cif_path: './data/2d_0621_train_18k/cif_structure'
      converter_cfg:
        cutoff: 4.0
        method: comformer_graph
        num_cpus: 10
      transforms:
        - Normalize:
            mean: -1.3171
            std: 1.2241
            apply_keys: "formation_energy_per_atom" # apply normalization to this property
        - ClipData:
            min: -6.0
            apply_keys: "formation_energy_per_atom" # apply clip to this property
    sampler:
      __name__: BatchSampler
      shuffle: False
      drop_last: False
      batch_size: 64
  predict:
    dataset:
      __name__: CIFDataset
      csv_path: "./data/2d_0621_train_18k/val.csv"
      cif_path: './data/2d_0621_train_18k/cif_structure'
      converter_cfg:
        cutoff: 4.0
        method: comformer_graph
        num_cpus: 10
    sampler:
      __name__: BatchSampler
      shuffle: False
      drop_last: False
      batch_size: 16
